name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # t√§glich
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: A-Schlagan
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Commit and push to main
        run: |
          cp -r dist/* .    # Snake SVGs ins Repo kopieren
          git add snake.svg snake-dark.svg
          git commit -m "Update Snake animation" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
